#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat:
    build:
      context: .
      args:
        GIT_SUPPORT: "yes"
    environment:
      CVAT_HEADLESS_USERNAME: "cvat"
      CVAT_HEADLESS_EMAIL: "cvat@example.com"
